name: tasbih_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  http: ^1.2.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/tasbeeh2.png"
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/pop-up-sound.mp3
    - assets/analog-sound.mp3
    - assets/setting_.png
    - assets/qrn.png
    - assets/islamicDua.png
    - assets/adhan_.png
    - assets/tasbih_.png
    - assets/dua.png
    - assets/hadith.png
    - assets/house.png
    - assets/info.png
